name: Build iOS

on: 
  workflow_dispatch:
    inputs:
      notes:
        type: string
        description: Release Notes
      upload-artifact:
        description: "Get an artifact to download"
        type: choice
        default: 'false'
        options:
          - true
          - false
      release:
        description: "Release Candidate"
        type: choice
        default: 'false'
        options:
          - true
          - false

jobs:
  build:
    uses: jd-boiv-in/unity-github-actions/.github/workflows/ios.yml@v1
    secrets: inherit
    with:
      runner: 'self-hosted' # 'ubuntu-latest'
      runner-extra: 'self-hosted' # 'ubuntu-latest'
      runner-sign: 'macos-13'
      il2cpp: '1'
      library: 'Library-iOS'
      artifact: 'build-ios'
      s3-folder: 'ios'
      discord: 'iOS'
      timeout: 45
      notes: ${{ inputs.notes }}
      release: ${{ inputs.release }}
      upload-artifact: ${{ inputs.upload-artifact }}
