name: Build Linux (mono)

on: 
  workflow_dispatch:
    inputs:
      notes:
        type: string
        description: Release Notes
      upload-artifact:
        description: "Get an artifact to download"
        type: choice
        default: 'false'
        options:
          - true
          - false
      release:
        description: "Release Candidate"
        type: choice
        default: 'false'
        options:
          - true
          - false

jobs:
  build:
    uses: jd-boiv-in/unity-github-actions/.github/workflows/linux.yml@v1
    secrets: inherit
    with:
      runner: 'self-hosted' # 'ubuntu-latest'
      runner-extra: 'self-hosted' # 'ubuntu-latest'
      il2cpp: '0'
      library: 'Library-LinuxMono'
      artifact: 'build-linux-mono'
      s3-folder: 'linux-mono'
      zip-suffix: '.linux-mono.zip'
      discord: 'Linux (mono)'
      timeout: 30
      notes: ${{ inputs.notes }}
      release: ${{ inputs.release }}
      upload-artifact: ${{ inputs.upload-artifact }}
