name: Build macOS (IL2CPP)

on: 
  workflow_dispatch:
    inputs:
      notes:
        type: string
        description: Release Notes
      upload-artifact:
        description: "Get an artifact to download"
        type: choice
        default: 'false'
        options:
          - true
          - false
      generate-appstore:
        description: "Release on AppStore / Testflight"
        type: choice
        default: 'true'
        options:
          - true
          - false
      generate-dmg:
        description: "Create a DMG"
        type: choice
        default: 'true'
        options:
          - true
          - false
      release:
        description: "Release Candidate"
        type: choice
        default: 'false'
        options:
          - true
          - false

jobs:
  build:
    uses: jd-boiv-in/unity-github-actions/.github/workflows/macos.yml@v1
    secrets: inherit
    with:
      runner: 'ubuntu-latest'
      runner-extra: 'ubuntu-latest'
      runner-sign: 'macos-13'
      il2cpp: '1'
      library: 'Library-MacOS'
      artifact: 'build-macos'
      s3-folder: 'macos'
      zip-suffix: '.macos.zip'
      dmg-suffix: '.dmg'
      discord: 'macOS (IL2CPP)'
      timeout: 45
      notes: ${{ inputs.notes }}
      release: ${{ inputs.release }}
      upload-artifact: ${{ inputs.upload-artifact }}
      generate-appstore: ${{ inputs.generate-appstore }}
      generate-dmg: ${{ inputs.generate-dmg }}
